POST http://localhost:3003/users
Content-Type: application/json

{
"name": "perola",
"email": "perola@example.com",
"password": "123456"

}
###
GET http://localhost:3003/users

###
POST http://localhost:3003/products
Content-Type: application/json

{
    "name": "Calça prada efeito lipo",
    "price": "119.90",
    "image_url": "https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ"

}

###
GET http://localhost:3003/products

###
POST http://localhost:3003/purchases
Content-Type: application/json
{
"user_id":"123",
"product_id": "123",
"quantity": 5

}
